# Generated by Django 6.1 on 2026-09-22 21:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=80, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(?:[.\\-][a-z0-9]+)*$', 'Use lowercase words separated by dots or hyphens, like «clocking.general».')], verbose_name='slug')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('ca', 'Català'), ('gl', 'Galego')], max_length=2, verbose_name='language')),
                ('title', models.CharField(max_length=160, verbose_name='title')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'help article',
                'verbose_name_plural': 'help articles',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='HelpBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('kind', models.CharField(choices=[('paragraph', 'Paragraph'), ('heading', 'Heading'), ('list', 'List'), ('callout', 'Callout')], max_length=20, verbose_name='kind')),
                ('data', models.JSONField(default=dict, verbose_name='content')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='help.helparticle', verbose_name='article')),
            ],
            options={
                'verbose_name': 'help block',
                'verbose_name_plural': 'help blocks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HelpSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-z0-9]+(?:[.\\-][a-z0-9]+)*$', 'Use lowercase words separated by dots or hyphens, like «clocking.general».')], verbose_name='slug')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'English'), ('ca', 'Català'), ('gl', 'Galego')], max_length=2, verbose_name='language')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'help section',
                'verbose_name_plural': 'help sections',
                'ordering': ['order', 'title'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'language'), name='unique_help_section_per_language')],
            },
        ),
        migrations.AddField(
            model_name='helparticle',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='help.helpsection', verbose_name='section'),
        ),
        migrations.AddConstraint(
            model_name='helparticle',
            constraint=models.UniqueConstraint(fields=('slug', 'language'), name='unique_help_article_per_language'),
        ),
    ]
