# Generated by Django 6.1 on 2026-08-11 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('absence_type', models.CharField(choices=[('VACATION', 'Holiday'), ('SICK_LEAVE', 'Sick leave'), ('PERSONAL', 'Personal leave'), ('OTHER', 'Other')], max_length=20, verbose_name='type')),
                ('start_date', models.DateField(verbose_name='from')),
                ('end_date', models.DateField(verbose_name='to')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10, verbose_name='status')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('justification', models.FileField(blank=True, upload_to='justifications/%Y/%m/', verbose_name='supporting document')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_resolved', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'absence',
                'verbose_name_plural': 'absences',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['tenant', 'employee', 'status'], name='absences_ab_tenant__827b27_idx'), models.Index(fields=['employee', 'status', 'start_date', 'end_date'], name='absences_ab_employe_71d7dc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='absence_ends_after_it_starts')],
            },
        ),
    ]
