# Generated by Django 6.1 on 2026-08-11 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0001_initial'),
        ('tenants', '0003_tenant_record_retention_years_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='justification',
            field=models.FileField(blank=True, help_text='Not available for sick leave: the medical certificate is not stored here. Since RD 1060/2022 the worker no longer hands it to the employer --- the INSS sends the data to the company directly.', upload_to='justifications/%Y/%m/', verbose_name='supporting document'),
        ),
        migrations.AddConstraint(
            model_name='absence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('absence_type', 'SICK_LEAVE'), _negated=True), ('justification', ''), _connector='OR'), name='no_medical_certificate_is_stored'),
        ),
    ]
