# Generated by Django 6.1 on 2026-08-12 20:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0003_justification_limits'),
        ('tenants', '0015_publicholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='to (time)'),
        ),
        migrations.AddField(
            model_name='absence',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='from (time)'),
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(blank=True, max_length=40, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('family', models.CharField(choices=[('VACATION', 'Holiday'), ('SICK_LEAVE', 'Sick leave'), ('PAID_LEAVE', 'Paid leave'), ('UNPAID_LEAVE', 'Unpaid leave')], default='PAID_LEAVE', help_text='What it behaves like. Holiday spends the holiday balance; sick leave never stores a certificate.', max_length=14, verbose_name='kind')),
                ('basis', models.CharField(blank=True, help_text='The article it comes from. Empty for one the agreement gives.', max_length=60, verbose_name='legal basis')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Empty means the indispensable time, with no fixed limit.', max_digits=6, null=True, verbose_name='how much')),
                ('unit', models.CharField(choices=[('DAYS_CALENDAR', 'calendar days'), ('DAYS_WORKING', 'working days'), ('HOURS', 'hours'), ('WEEKS', 'weeks')], default='DAYS_CALENDAR', max_length=14, verbose_name='in')),
                ('period', models.CharField(choices=[('EVENT', 'each time'), ('DAY', 'a day'), ('WEEK', 'a week'), ('MONTH', 'a month'), ('YEAR', 'a year')], default='EVENT', max_length=6, verbose_name='per')),
                ('extra_when_travelling', models.DecimalField(decimal_places=1, default=0, help_text='Art. 37.3.b bis adds two days when the event needs a journey.', max_digits=4, verbose_name='extra if travelling')),
                ('paid', models.BooleanField(default=True, verbose_name='paid')),
                ('needs_justification', models.BooleanField(default=False, verbose_name='needs a supporting document')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'leave type',
                'verbose_name_plural': 'leave types',
                'ordering': ['family', 'name'],
            },
        ),
        migrations.AddField(
            model_name='absence',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='absences.leavetype', verbose_name='leave type'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('tenant', 'code'), name='one_leave_type_per_code'),
        ),
    ]
