# Generated by Django 6.1 on 2026-08-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0004_absence_end_time_absence_start_time_leavetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='absence_type',
            field=models.CharField(choices=[('VACATION', 'Holiday'), ('SICK_LEAVE', 'Sick leave'), ('PAID_LEAVE', 'Paid leave'), ('UNPAID_LEAVE', 'Unpaid leave'), ('PERSONAL', 'Personal leave'), ('OTHER', 'Other')], max_length=20, verbose_name='type'),
        ),
    ]
