# Generated by Django 6.1 on 2026-08-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0005_alter_absence_absence_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='reduction_share',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only for a suspension that reduces the working day instead of stopping it. Empty means the whole day. 40 means they still work 60 %.', max_digits=5, null=True, verbose_name='share reduced (%)'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='absence_type',
            field=models.CharField(choices=[('VACATION', 'Holiday'), ('SICK_LEAVE', 'Sick leave'), ('PAID_LEAVE', 'Paid leave'), ('UNPAID_LEAVE', 'Unpaid leave'), ('SUSPENSION', 'Contract suspended'), ('PERSONAL', 'Personal leave'), ('OTHER', 'Other')], max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='family',
            field=models.CharField(choices=[('VACATION', 'Holiday'), ('SICK_LEAVE', 'Sick leave'), ('PAID_LEAVE', 'Paid leave'), ('UNPAID_LEAVE', 'Unpaid leave'), ('SUSPENSION', 'Contract suspended')], default='PAID_LEAVE', help_text='What it behaves like. Holiday spends the holiday balance; sick leave never stores a certificate.', max_length=14, verbose_name='kind'),
        ),
    ]
