# Generated by Django 6.1 on 2026-08-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0006_absence_reduction_share_alter_absence_absence_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='initiated_by',
            field=models.CharField(choices=[('PERSON', 'The person requests it'), ('COMPANY', 'The company records it')], default='PERSON', max_length=8, verbose_name='who records it'),
        ),
    ]
