# Generated by Django 6.1 on 2026-08-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0007_leavetype_initiated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='vacation_recovery',
            field=models.CharField(blank=True, choices=[('UNLIMITED', 'Yes, with no deadline'), ('EIGHTEEN_MONTHS', 'Yes, within eighteen months')], help_text='Whether overlapping with booked holiday gives the right to take it later, and by when. Art. 38.3 ET sets two different regimes.', max_length=20, verbose_name='recovers holiday'),
        ),
    ]
