# Generated by Django 6.1 on 2026-08-13 13:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0008_leavetype_vacation_recovery'),
        ('tenants', '0016_workingtimerules_entry_tolerance_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveredHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('first_day', models.DateField(verbose_name='from')),
                ('last_day', models.DateField(verbose_name='to')),
                ('days', models.PositiveSmallIntegerField(verbose_name='days')),
                ('working_days', models.BooleanField(default=True, verbose_name='counted in working days')),
                ('regime', models.CharField(choices=[('UNLIMITED', 'No deadline (art. 38.3, second paragraph)'), ('EIGHTEEN_MONTHS', 'Eighteen months (art. 38.3, third paragraph)')], max_length=20, verbose_name='regime')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='must be taken by')),
                ('status', models.CharField(choices=[('PENDING', 'Waiting to be confirmed'), ('CONFIRMED', 'Confirmed'), ('DISMISSED', 'Not applicable')], db_index=True, default='PENDING', max_length=12, verbose_name='status')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='confirmed at')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_recoveries_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='confirmed by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovered_holidays', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='absences.absence', verbose_name='holiday affected')),
                ('sick_leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries_caused', to='absences.absence', verbose_name='leave that overlapped')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'recovered holiday',
                'verbose_name_plural': 'recovered holidays',
                'constraints': [models.UniqueConstraint(fields=('holiday', 'sick_leave', 'first_day'), name='one_recovery_per_overlap')],
            },
        ),
    ]
