# Generated by Django 6.1 on 2026-08-26 04:08

import apps.absences.uploads
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0010_absence_requested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='justification',
            field=models.FileField(blank=True, help_text='Not available for sick leave: the medical certificate is not stored here. Since RD 1060/2022 the worker no longer hands it to the employer --- the INSS sends the data to the company directly.', upload_to='justifications/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'heic', 'heif'], message='Only a PDF or an image: %(allowed_extensions)s.'), apps.absences.uploads.validate_content, apps.absences.uploads.validate_size], verbose_name='supporting document'),
        ),
    ]
