# Generated by Django 6.1 on 2026-08-26 12:28

import apps.common.texto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0011_alter_absence_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='reason',
            field=models.TextField(blank=True, validators=[apps.common.texto.validate_texto_legible], verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='note',
            field=models.TextField(blank=True, validators=[apps.common.texto.validate_texto_legible], verbose_name='note'),
        ),
    ]
