# Generated by Django 6.1 on 2026-08-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absences', '0012_alter_absence_reason_alter_leavetype_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10, verbose_name='status'),
        ),
    ]
