# Generated by Django 6.1 on 2026-08-13 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0016_workingtimerules_entry_tolerance_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='endpoint')),
                ('p256dh', models.CharField(max_length=200, verbose_name='public key')),
                ('auth', models.CharField(max_length=100, verbose_name='authentication secret')),
                ('device_label', models.CharField(blank=True, max_length=80, verbose_name='device')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='last used')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'push subscription',
                'verbose_name_plural': 'push subscriptions',
            },
        ),
    ]
