# Generated by Django 6.1 on 2026-08-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='annual_leave_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Overrides the company figure for this person. Empty means the company's. Part-time and mid-year joiners are the usual reason.", null=True, verbose_name='annual leave days'),
        ),
    ]
