# Generated by Django 6.1 on 2026-08-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_annual_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contracted_schedule',
            field=models.CharField(blank=True, help_text="Art. 3.b: the agreed working hours, as text. For example 'L-V 09:00-17:00'. Free text because a schedule is not a shape a closed field can hold.", max_length=200, verbose_name='agreed hours'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_work_mode',
            field=models.CharField(choices=[('ONSITE', 'On site'), ('REMOTE', 'Remote')], default='ONSITE', help_text='Art. 3.e. What a clock event assumes when it says nothing; each event can still record the other.', max_length=8, verbose_name='usual mode'),
        ),
        migrations.AddField(
            model_name='user',
            name='part_time',
            field=models.BooleanField(default=False, help_text='Art. 3.b. Part-time work is counted differently (art. 12 ET).', verbose_name='part time'),
        ),
        migrations.AddField(
            model_name='user',
            name='part_time_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only for part time. Art. 3.b asks for it explicitly.', max_digits=5, null=True, verbose_name='percentage of a full day'),
        ),
    ]
