# Generated by Django 6.1 on 2026-08-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_contracted_schedule_user_default_work_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_worker_representative',
            field=models.BooleanField(default=False, help_text='Informed when somebody disagrees with a change to their record (art. 4.b), and entitled to consult the register (art. 6.2).', verbose_name="workers' representative"),
        ),
    ]
