# Generated by Django 6.1 on 2026-08-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_worker_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Only used to apply the protections the law gives workers under eighteen: eight hours a day, a thirty-minute break from four and a half, two days of weekly rest, and no night work or overtime. Without it those protections cannot be applied, and the system says so rather than assuming the person is an adult.', null=True, verbose_name='date of birth'),
        ),
    ]
