# Generated by Django 6.1 on 2026-08-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='part_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='part_time_percentage',
        ),
        migrations.AddField(
            model_name='user',
            name='contract_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('VARIABLE', 'No fixed hours')], default='FULL_TIME', help_text='Art. 3.b: the working-time regime.', max_length=12, verbose_name='contract'),
        ),
        migrations.AddField(
            model_name='user',
            name='contracted_weekly_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="What the contract agreed. Empty on a full-time contract means the company's figure, and on one with no fixed hours means there is none.", max_digits=4, null=True, verbose_name='contracted hours a week'),
        ),
    ]
