# Generated by Django 6.1 on 2026-08-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_contract_type_and_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contracted_weekly_hours',
        ),
        migrations.AddField(
            model_name='user',
            name='contracted_hours',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="The figure the contract agreed. Empty on a full-time contract means the company's own; empty with no agreed figure means there is none.", max_digits=6, null=True, verbose_name='contracted hours'),
        ),
        migrations.AddField(
            model_name='user',
            name='contracted_period',
            field=models.CharField(choices=[('WEEK', 'a week'), ('MONTH', 'a month'), ('YEAR', 'a year')], default='WEEK', help_text='Whether the figure above is a week, a month or a year.', max_length=8, verbose_name='over'),
        ),
        migrations.AddField(
            model_name='user',
            name='regime',
            field=models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('REDUCED', 'Reduced working day'), ('TRAINING', 'Training contract'), ('VARIABLE', 'No agreed figure')], default='FULL_TIME', help_text='Art. 3.b. Decides which limits apply, not just how many hours.', max_length=12, verbose_name='working-time regime'),
        ),
    ]
