# Generated by Django 6.1 on 2026-08-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_working_time_regime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contract_end',
            field=models.DateField(blank=True, help_text='Empty means open-ended. A date makes it fixed-term.', null=True, verbose_name='contract ends'),
        ),
        migrations.AddField(
            model_name='user',
            name='contract_start',
            field=models.DateField(blank=True, help_text='Empty means it was already running when the company started here.', null=True, verbose_name='contract starts'),
        ),
        migrations.AddField(
            model_name='user',
            name='seasonal',
            field=models.BooleanField(default=False, help_text='Art. 16 ET: the work comes in periods of activity. Outside them there is no expected working day, and the roster says so instead of reporting an absence.', verbose_name='permanent seasonal'),
        ),
    ]
