# Generated by Django 6.1 on 2026-08-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_contract_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='night_worker',
            field=models.CharField(choices=[('AUTO', 'Read from the roster'), ('YES', 'Yes'), ('NO', 'No')], default='AUTO', help_text='Art. 36.1 ET. A status, not a shift: three hours of the daily working day at night as a rule, or a third of the year. It brings an eight-hour average over fifteen days and a ban on overtime. Leave it on automatic to read it from the roster.', max_length=6, verbose_name='night worker'),
        ),
        migrations.AddField(
            model_name='user',
            name='rotating_shifts',
            field=models.BooleanField(default=False, help_text='Art. 36.3 ET. The person rotates between shift teams. This does not add limits: it stops the ordinary ones being applied to a changeover, where a shorter rest is lawful and owed back rather than a breach.', verbose_name='rotating shifts'),
        ),
        migrations.AddField(
            model_name='user',
            name='voluntary_night_shift',
            field=models.BooleanField(default=False, help_text='Art. 36.3 ET allows more than two consecutive weeks on the night shift only when the person asked for it. Recorded here because the roster cannot tell a volunteer from somebody left there.', verbose_name='volunteered for nights'),
        ),
    ]
