# Generated by Django 6.1 on 2026-08-12 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_night_worker_user_rotating_shifts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='managers',
            field=models.ManyToManyField(blank=True, help_text='Who may read and resolve for the people in it. Only has an effect on the manager profile: an administrator sees the whole company.', related_name='departments_managed', to=settings.AUTH_USER_MODEL, verbose_name='managers'),
        ),
    ]
