# Generated by Django 6.1 on 2026-08-12 19:49

import apps.tenants.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_tenant_managers_see_whole_company'),
        ('users', '0010_department_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('municipality', models.CharField(blank=True, help_text='Decides the two local public holidays.', max_length=120, verbose_name='municipality')),
                ('municipality_code', models.CharField(blank=True, help_text='INE code in Spain. Names repeat between provinces; codes do not.', max_length=10, verbose_name='municipality code')),
                ('region', models.CharField(blank=True, help_text='Decides the public holidays the region sets. Empty uses only the national ones.', max_length=8, verbose_name='region')),
                ('time_zone', models.CharField(blank=True, help_text="Empty uses the company's. Only needed where a workplace is in another zone: in Spain, the Canary Islands.", max_length=64, validators=[apps.tenants.models.validate_time_zone], verbose_name='time zone')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'workplace',
                'verbose_name_plural': 'workplaces',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='users.workplace', verbose_name='workplace'),
        ),
        migrations.AddConstraint(
            model_name='workplace',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_workplace_per_company'),
        ),
    ]
