# Generated by Django 6.1 on 2026-08-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_workplace_user_workplace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wants_punch_reminders',
            field=models.BooleanField(default=True, help_text='Send a reminder when a shift starts and there is no entry, or when a day is left open. It prompts the real punch; it never records one.', verbose_name='wants clock reminders'),
        ),
    ]
