# Generated by Django 6.1 on 2026-08-26 12:28

import apps.common.texto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_oidc_sub_user_unique_identity_per_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, validators=[apps.common.texto.validate_texto_legible], verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, validators=[apps.common.texto.validate_texto_legible], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, validators=[apps.common.texto.validate_texto_legible], verbose_name='last name'),
        ),
    ]
