# Generated by Django 6.1 on 2026-08-27 12:05

import django.db.models.functions.text
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower


def negarse_si_hay_choques(apps, schema_editor):
    """Se planta antes de crear el índice si dos números chocan por la caja.

    Sin esto, la creación del índice único falla en la base con un mensaje que
    dice que hay duplicados y no dice **cuáles**, dejando el despliegue a medias
    y a quien lo lanzó buscando a ciegas.

    En la base de desarrollo hay cero choques, y por eso esto no es una
    comprobación teórica: es lo que hace que un despliegue con datos reales
    pueda arreglarse en un minuto en vez de en una tarde.
    """
    User = apps.get_model("users", "User")
    choques = (
        User.objects.exclude(employee_id="")
        .annotate(numero=Lower("employee_id"))
        .values("tenant_id", "numero")
        .annotate(cuantos=Count("id"))
        .filter(cuantos__gt=1)
        .order_by("tenant_id", "numero")
    )
    if not choques:
        return

    Tenant = apps.get_model("tenants", "Tenant")
    nombres = dict(Tenant.objects.values_list("id", "name"))
    detalle = []
    for fila in choques:
        quienes = (
            User.objects.filter(tenant_id=fila["tenant_id"])
            .annotate(numero=Lower("employee_id"))
            .filter(numero=fila["numero"])
            .values_list("employee_id", "email")
        )
        gente = ", ".join(f"«{num}» {correo}" for num, correo in quienes)
        detalle.append(
            f"  · {nombres.get(fila['tenant_id'], fila['tenant_id'])}: "
            f"{fila['cuantos']} personas con el número «{fila['numero']}» -> {gente}"
        )

    raise RuntimeError(
        "El número de empleado va a pasar a ser único sin distinguir mayúsculas, "
        "y hay números que chocan:\n"
        + "\n".join(detalle)
        + "\n\nNo se ha cambiado nada. Cambia el número de una de las personas de "
        "cada línea y vuelve a lanzar la migración. Se hace así, y no eligiendo "
        "una por su cuenta, porque quién se queda el número lo decide la empresa: "
        "el número identifica a la persona en sus nóminas y en su convenio."
    )


def no_hay_nada_que_deshacer(apps, schema_editor):
    """La comprobación no escribe, así que volver atrás no tiene que limpiar."""


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tenants", "0025_computationrulechange"),
        ("users", "0015_alter_department_description_alter_user_first_name_and_more"),
    ]

    operations = [
        # Primero mirar, luego tocar: si hay choques esto se planta y la base se
        # queda como estaba.
        migrations.RunPython(negarse_si_hay_choques, no_hay_nada_que_deshacer),
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_staff_number_per_company",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("employee_id"),
                models.F("tenant"),
                condition=models.Q(("employee_id", ""), _negated=True),
                name="unique_staff_number_per_company",
            ),
        ),
    ]
