# Generated by Django 6.1 on 2026-08-28 07:44

import apps.common.texto
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0026_alter_tenant_record_retention_years'),
        ('users', '0016_remove_user_unique_staff_number_per_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('start_date', models.DateField(verbose_name='activity starts')),
                ('end_date', models.DateField(blank=True, help_text='Empty while the season is open: a campaign knows when it starts.', null=True, verbose_name='activity ends')),
                ('called_on', models.DateField(blank=True, help_text='Art. 16.3 ET: the call-up is in writing and with notice. The date is what shows the notice was given; a tick would not.', null=True, verbose_name='called up on')),
                ('note', models.TextField(blank=True, validators=[apps.common.texto.validate_texto_legible], verbose_name='note')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_periods', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'period of activity',
                'verbose_name_plural': 'periods of activity',
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='activity_period_ends_after_it_starts')],
            },
        ),
    ]
