# Generated by Django 6.1 on 2026-08-28 10:58

import apps.common.texto
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0026_alter_tenant_record_retention_years'),
        ('users', '0017_activityperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteWorkAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('signed_on', models.DateField(help_text='Art. 5.1: the agreement comes before the remote work starts.', verbose_name='signed on')),
                ('starts_on', models.DateField(verbose_name='remote work starts')),
                ('ends_on', models.DateField(blank=True, help_text='Empty for an open-ended agreement, which is the usual one.', null=True, verbose_name='remote work ends')),
                ('agreed_share', models.DecimalField(blank=True, decimal_places=2, help_text='Art. 7.f asks the agreement to state it. Left empty it is not checked against what is actually worked: the figure that binds is on paper.', max_digits=5, null=True, verbose_name='share agreed (%)')),
                ('note', models.TextField(blank=True, validators=[apps.common.texto.validate_texto_legible], verbose_name='note')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remote_work_agreements', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'remote work agreement',
                'verbose_name_plural': 'remote work agreements',
                'ordering': ['-starts_on'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='remote_agreement_ends_after_it_starts')],
            },
        ),
    ]
