# Generated by Django 6.1 on 2026-08-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remoteworkagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='regime',
            field=models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('REDUCED', 'Reduced working day'), ('TRAINING_ALT', 'Training contract, alternating'), ('TRAINING_PRO', 'Training contract, work practice'), ('TRAINING', 'Training contract, kind not stated'), ('VARIABLE', 'No agreed figure')], default='FULL_TIME', help_text='Art. 3.b. Decides which limits apply, not just how many hours.', max_length=12, verbose_name='working-time regime'),
        ),
    ]
