# Generated by Django 6.1 on 2026-08-28 12:10

import apps.common.texto
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0026_alter_tenant_record_retention_years'),
        ('users', '0019_alter_user_regime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleAdaptation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('requested_on', models.DateField(help_text='The fifteen days of art. 34.8 count from here.', verbose_name='requested on')),
                ('asked_for', models.TextField(help_text='Duration, distribution, or the way the work is done --- remote included.', validators=[apps.common.texto.validate_texto_legible], verbose_name='what is being asked')),
                ('status', models.CharField(choices=[('PENDING', 'In negotiation'), ('ACCEPTED', 'Accepted'), ('ALTERNATIVE', 'An alternative was proposed'), ('REFUSED', 'Refused'), ('WITHDRAWN', 'Withdrawn by the person')], default='PENDING', max_length=12, verbose_name='status')),
                ('answered_on', models.DateField(blank=True, null=True, verbose_name='answered on')),
                ('answer', models.TextField(blank=True, help_text='Art. 34.8 asks for this in writing, and for a reason when the answer is not a plain yes.', validators=[apps.common.texto.validate_texto_legible], verbose_name='answer')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_adaptations_answered', to=settings.AUTH_USER_MODEL, verbose_name='answered by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_adaptations', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'schedule adaptation',
                'verbose_name_plural': 'schedule adaptations',
                'ordering': ['-requested_on'],
                'constraints': [models.CheckConstraint(condition=models.Q(('answered_on__isnull', True), ('answered_on__gte', models.F('requested_on')), _connector='OR'), name='adaptation_answered_after_it_was_asked')],
            },
        ),
    ]
