# Generated by Django 6.1 on 2026-08-28 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_scheduleadaptation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relieves',
            field=models.ForeignKey(blank=True, help_text='Art. 12.7: who this relief contract stands in for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relieved_by', to=settings.AUTH_USER_MODEL, verbose_name='relieves'),
        ),
    ]
