# Generated by Django 6.1 on 2026-08-29 00:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0031_workingtimerules_seniority_leave'),
        ('users', '0021_user_relieves'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('starts_on', models.DateField(blank=True, help_text='Empty means it is not on record since when, so it counts for any period.', null=True, verbose_name='from')),
                ('ends_on', models.DateField(blank=True, help_text='Empty means it is the current one.', null=True, verbose_name='until')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.department', verbose_name='department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_history', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'department assignment',
                'verbose_name_plural': 'department assignments',
                'ordering': ['-starts_on'],
                'indexes': [models.Index(fields=['employee', 'starts_on', 'ends_on'], name='users_depar_employe_c3a00b_idx')],
            },
        ),
    ]
