# Generated by Django 6.1 on 2026-09-18 01:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0036_tenant_offline_punch_grace_hours'),
        ('users', '0022_departmentassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkplaceAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('starts_on', models.DateField(blank=True, help_text='Empty means it is not on record since when, so it counts for any period.', null=True, verbose_name='from')),
                ('ends_on', models.DateField(blank=True, help_text='Empty means it is the current one.', null=True, verbose_name='until')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplace_history', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='users.workplace', verbose_name='workplace')),
            ],
            options={
                'verbose_name': 'workplace assignment',
                'verbose_name_plural': 'workplace assignments',
                'ordering': ['-starts_on'],
                'indexes': [models.Index(fields=['employee', 'starts_on', 'ends_on'], name='users_workp_employe_853f86_idx')],
            },
        ),
    ]
