# Generated by Django 6.1 on 2026-09-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_workplaceassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('ADMIN', 'Administrator'), ('ADVISOR', 'Labour advisor')], default='EMPLOYEE', max_length=20, verbose_name='role'),
        ),
    ]
