# Generated by Django 6.1 on 2026-09-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rol_asesoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_support',
            field=models.BooleanField(default=False, editable=False, verbose_name='support access'),
        ),
    ]
