# Generated by Django 6.1 on 2026-08-11 14:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('punch_type', models.CharField(choices=[('IN', 'Clock in'), ('OUT', 'Clock out')], max_length=3, verbose_name='type')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='timestamp')),
                ('source', models.CharField(choices=[('WEB', 'Web panel'), ('MOBILE', 'Mobile app'), ('APPLICATION', 'External application, employee identity'), ('DELEGATED', 'External application, on behalf of the employee'), ('TERMINAL', 'Shared terminal'), ('ADMIN', 'Manual correction by an administrator'), ('IMPORT', 'Data import')], default='WEB', max_length=16, verbose_name='source')),
                ('source_application', models.CharField(blank=True, help_text='Which application recorded it, when it was not this one.', max_length=100, verbose_name='source application')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('device_id', models.CharField(blank=True, max_length=100, verbose_name='device')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='user agent')),
                ('hash_integrity', models.CharField(editable=False, max_length=64, verbose_name='integrity hash')),
                ('is_active', models.BooleanField(default=True, verbose_name='valid')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='voided at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punches', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Set when somebody other than the employee created the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punches_recorded', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='punches.punch', verbose_name='replaced by')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'clock event',
                'verbose_name_plural': 'clock events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', 'employee', '-timestamp'], name='punches_pun_tenant__d734eb_idx'), models.Index(fields=['tenant', '-timestamp'], name='punches_pun_tenant__7fef0d_idx'), models.Index(fields=['employee', 'is_active', '-timestamp'], name='punches_pun_employe_496670_idx')],
            },
        ),
    ]
