# Generated by Django 6.1 on 2026-08-11 16:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punches', '0001_initial'),
        ('tenants', '0002_application_applicationcredential_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('kind', models.CharField(choices=[('ADD', 'Add a missing event'), ('MODIFY', 'Change the time of an event'), ('VOID', 'Void an event that should not exist')], max_length=8, verbose_name='kind')),
                ('proposed_type', models.CharField(blank=True, choices=[('IN', 'Clock in'), ('OUT', 'Clock out')], max_length=3, verbose_name='type')),
                ('proposed_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='proposed time')),
                ('reason', models.TextField(help_text='Why the record does not match what happened. Required.', verbose_name='reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8, verbose_name='status')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('resolution_note', models.TextField(blank=True, verbose_name='resolution note')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections_requested', to=settings.AUTH_USER_MODEL, verbose_name='requested by')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections_resolved', to=settings.AUTH_USER_MODEL, verbose_name='resolved by')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_correction', to='punches.punch', verbose_name='resulting event')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_requests', to='punches.punch', verbose_name='event concerned')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'record correction',
                'verbose_name_plural': 'record corrections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', '-created_at'], name='punches_pun_tenant__6215bc_idx'), models.Index(fields=['employee', '-created_at'], name='punches_pun_employe_9a46a6_idx')],
            },
        ),
    ]
