# Generated by Django 6.1 on 2026-08-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punches', '0003_punch_hash_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='flexibility_measure',
            field=models.CharField(blank=True, choices=[('', 'None'), ('CARE', 'Care or family reasons (art. 34.8 ET)'), ('FLEXITIME', 'Flexible hours'), ('IRREGULAR', 'Irregular distribution (art. 34.2 ET)'), ('OTHER', 'Another arrangement')], default='', max_length=16, verbose_name='arrangement'),
        ),
        migrations.AddField(
            model_name='punch',
            name='force_majeure',
            field=models.BooleanField(default=False, help_text='Art. 35.3 ET: hours worked to prevent or repair accidents and other extraordinary and urgent damage. They do not count towards the annual overtime limit, so they have to be distinguishable.', verbose_name='to prevent or repair urgent damage'),
        ),
        migrations.AddField(
            model_name='punch',
            name='hours_nature',
            field=models.CharField(choices=[('ORDINARY', 'Ordinary'), ('OVERTIME', 'Overtime'), ('COMPLEMENTARY', 'Complementary')], default='ORDINARY', max_length=16, verbose_name='nature of the hours'),
        ),
        migrations.AddField(
            model_name='punch',
            name='interval',
            field=models.CharField(choices=[('WORK', 'Working day'), ('BREAK', 'Break that is not working time'), ('STANDBY', 'Waiting or on-call time'), ('DISCONNECTION', 'Interruption of the right to disconnect')], default='WORK', max_length=16, verbose_name='interval'),
        ),
        migrations.AddField(
            model_name='punch',
            name='overtime_settlement',
            field=models.CharField(blank=True, choices=[('REST', 'Compensated with rest'), ('PAID', 'Paid')], help_text='Required for overtime: art. 3.f asks whether it is rested or paid.', max_length=8, verbose_name='how the overtime is settled'),
        ),
        migrations.AddField(
            model_name='punch',
            name='work_mode',
            field=models.CharField(choices=[('ONSITE', 'On site'), ('REMOTE', 'Remote')], default='ONSITE', max_length=8, verbose_name='mode'),
        ),
        migrations.AlterField(
            model_name='punch',
            name='hash_version',
            field=models.PositiveSmallIntegerField(default=3, editable=False, verbose_name='hash version'),
        ),
    ]
