# Generated by Django 6.1 on 2026-08-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punches', '0004_punch_flexibility_measure_punch_force_majeure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchcorrection',
            name='applied_without_agreement',
            field=models.BooleanField(default=False, help_text='The change went in anyway, which art. 4.b allows. It travels to the inspection report: a reader has to be able to tell a correction both parties accepted from one imposed over an objection.', verbose_name='applied without agreement'),
        ),
        migrations.AddField(
            model_name='punchcorrection',
            name='employee_agreed',
            field=models.BooleanField(blank=True, help_text='Art. 4.b: a change needs the authorisation of the company and of the person concerned. Empty means they have not answered.', null=True, verbose_name='the person agrees'),
        ),
        migrations.AddField(
            model_name='punchcorrection',
            name='employee_dissent',
            field=models.TextField(blank=True, help_text='Their version, kept beside the change and never instead of it. Art. 4.b lets the company record the modification and the person their disagreement, so the record holds both.', verbose_name="the person's account"),
        ),
        migrations.AddField(
            model_name='punchcorrection',
            name='employee_responded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='answered at'),
        ),
        migrations.AddField(
            model_name='punchcorrection',
            name='representatives_notice',
            field=models.CharField(blank=True, help_text="Art. 4.b requires informing the workers' legal representation when there is disagreement. If the company has not said who they are, that is recorded here rather than passed over in silence.", max_length=200, verbose_name='how they were informed'),
        ),
        migrations.AddField(
            model_name='punchcorrection',
            name='representatives_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="workers' representatives informed at"),
        ),
        migrations.AlterField(
            model_name='punchcorrection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting for the company'), ('AWAITING_EMPLOYEE', 'Waiting for the person concerned'), ('APPROVED', 'Applied with agreement'), ('DISPUTED', 'Applied without agreement, with the disagreement recorded'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='status'),
        ),
    ]
