# Generated by Django 6.1 on 2026-08-13 07:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punches', '0005_punchcorrection_applied_without_agreement_and_more'),
        ('tenants', '0016_workingtimerules_entry_tolerance_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='evidence',
            field=models.JSONField(blank=True, default=dict, help_text='What proves the trigger: coordinates, a network name, an external event id.', verbose_name='trigger evidence'),
        ),
        migrations.AddField(
            model_name='punch',
            name='trigger',
            field=models.CharField(choices=[('MANUAL', 'A person pressed the button'), ('GEOFENCE', 'Entering or leaving a worksite'), ('NETWORK', 'Joining or leaving a work network'), ('SENSOR', "Another system's presence event")], default='MANUAL', max_length=8, verbose_name='trigger'),
        ),
        migrations.CreateModel(
            name='PunchReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('day', models.DateField(verbose_name='day')),
                ('kind', models.CharField(choices=[('CLOCK_IN', 'Missing entry'), ('CLOCK_OUT', 'Day left open')], max_length=10, verbose_name='kind')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='sent at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_reminders', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'clock reminder',
                'verbose_name_plural': 'clock reminders',
                'constraints': [models.UniqueConstraint(fields=('employee', 'day', 'kind'), name='one_reminder_per_person_day_kind')],
            },
        ),
    ]
