# Generated by Django 6.1 on 2026-08-13 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punches', '0006_punch_evidence_punch_trigger_punchreminder'),
        ('tenants', '0016_workingtimerules_entry_tolerance_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('day', models.DateField(verbose_name='day')),
                ('minutes', models.PositiveIntegerField(verbose_name='overtime minutes ruled on')),
                ('status', models.CharField(choices=[('AUTHORISED', 'Authorised'), ('REJECTED', 'Not authorised')], max_length=10, verbose_name='status')),
                ('settlement', models.CharField(blank=True, choices=[('REST', 'Compensated with rest'), ('PAID', 'Paid')], max_length=4, verbose_name='settlement')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('decided_alone', models.BooleanField(default=False, verbose_name='decided alone')),
                ('decided_at', models.DateTimeField(auto_now=True, verbose_name='decided at')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overtime_decisions_made', to=settings.AUTH_USER_MODEL, verbose_name='decided by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_decisions', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'overtime decision',
                'verbose_name_plural': 'overtime decisions',
                'ordering': ['-day'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'day'), name='one_overtime_decision_per_person_day')],
            },
        ),
    ]
