# Generated by Django 6.1 on 2026-08-25 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punches', '0007_overtimedecision'),
        ('tenants', '0021_remove_tenantlimits_max_admins_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegatedPunchReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('key', models.CharField(max_length=200, verbose_name='idempotency key')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_receipts', to='tenants.application', verbose_name='application')),
                ('punch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='punches.punch', verbose_name='event')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'delegated punch receipt',
                'verbose_name_plural': 'delegated punch receipts',
                'constraints': [models.UniqueConstraint(fields=('application', 'key'), name='one_receipt_per_application_key')],
            },
        ),
    ]
