# Generated by Django 6.1 on 2026-08-26 12:28

import apps.common.texto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punches', '0008_delegatedpunchreceipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchcorrection',
            name='employee_dissent',
            field=models.TextField(blank=True, help_text='Their version, kept beside the change and never instead of it. Art. 4.b lets the company record the modification and the person their disagreement, so the record holds both.', validators=[apps.common.texto.validate_texto_legible], verbose_name="the person's account"),
        ),
        migrations.AlterField(
            model_name='punchcorrection',
            name='reason',
            field=models.TextField(help_text='Why the record does not match what happened. Required.', validators=[apps.common.texto.validate_texto_legible], verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='punchcorrection',
            name='resolution_note',
            field=models.TextField(blank=True, validators=[apps.common.texto.validate_texto_legible], verbose_name='resolution note'),
        ),
    ]
