# Generated by Django 6.1 on 2026-08-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punches', '0009_alter_punchcorrection_employee_dissent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchcorrection',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting for the company'), ('AWAITING_EMPLOYEE', 'Waiting for the person concerned'), ('APPROVED', 'Applied with agreement'), ('DISPUTED', 'Applied without agreement, with the disagreement recorded'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn by the company')], default='PENDING', max_length=20, verbose_name='status'),
        ),
    ]
