# Generated by Django 6.1 on 2026-08-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punches', '0010_alter_punchcorrection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='time_zone',
            field=models.CharField(blank=True, max_length=64, verbose_name='time zone'),
        ),
    ]
