# Generated by Django 6.1 on 2026-08-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("punches", "0011_punch_time_zone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="punch",
            name="hash_version",
            field=models.PositiveSmallIntegerField(
                default=4, editable=False, verbose_name="hash version"
            ),
        ),
    ]
