# Generated by Django 6.1 on 2026-09-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punches', '0012_alter_punch_hash_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='declared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='declared by the device'),
        ),
        migrations.AddField(
            model_name='punch',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='received at'),
        ),
        migrations.AlterField(
            model_name='punch',
            name='hash_version',
            field=models.PositiveSmallIntegerField(default=5, editable=False, verbose_name='hash version'),
        ),
    ]
