# Generated by Django 6.1 on 2026-08-12 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_workingtimerules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='when')),
                ('actor_label', models.CharField(blank=True, max_length=160, verbose_name='who (as recorded)')),
                ('action', models.CharField(choices=[('RECORD_VIEWED', "Read somebody else's record"), ('REPORT_EXPORTED', 'Exported a working time report'), ('DOCUMENT_DOWNLOADED', 'Downloaded a supporting document'), ('CORRECTION_REQUESTED', 'Requested a correction'), ('CORRECTION_APPROVED', 'Approved a correction'), ('CORRECTION_REJECTED', 'Rejected a correction'), ('PUNCH_VOIDED', 'Voided a clock event'), ('ABSENCE_APPROVED', 'Approved leave'), ('ABSENCE_REJECTED', 'Rejected leave'), ('PERSON_CREATED', 'Added a person'), ('PERSON_UPDATED', 'Changed a person'), ('PERSON_DEACTIVATED', 'Deactivated a person'), ('ROLE_CHANGED', 'Changed a role'), ('SETTINGS_CHANGED', 'Changed company settings'), ('RULES_CHANGED', 'Changed working time rules'), ('APPLICATION_CREATED', 'Registered an application'), ('APPLICATION_REVOKED', 'Revoked an application credential'), ('METADATA_PURGED', 'Purged security metadata'), ('SIGN_IN_FAILED', 'Failed sign-in')], db_index=True, max_length=32, verbose_name='action')),
                ('target_type', models.CharField(blank=True, max_length=32, verbose_name='type')),
                ('target_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='identifier')),
                ('target_label', models.CharField(blank=True, max_length=200, verbose_name='what (as recorded)')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='changes')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='who')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_entries', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'audit entry',
                'verbose_name_plural': 'audit trail',
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['tenant', '-at'], name='audit_audit_tenant__ab8b08_idx'), models.Index(fields=['tenant', 'action', '-at'], name='audit_audit_tenant__fc249c_idx'), models.Index(fields=['actor', '-at'], name='audit_audit_actor_i_d4a3da_idx')],
            },
        ),
    ]
