# Generated by Django 6.1 on 2026-08-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('RECORD_VIEWED', "Read somebody else's record"), ('REPORT_EXPORTED', 'Exported a working time report'), ('DOCUMENT_DOWNLOADED', 'Downloaded a supporting document'), ('CORRECTION_REQUESTED', 'Requested a correction'), ('CORRECTION_APPROVED', 'Approved a correction'), ('CORRECTION_REJECTED', 'Rejected a correction'), ('PUNCH_VOIDED', 'Voided a clock event'), ('CORRECTION_DISPUTED', 'Disagreed with a proposed change'), ('CORRECTION_IMPOSED', 'Applied a change without agreement'), ('ABSENCE_APPROVED', 'Approved leave'), ('ABSENCE_REJECTED', 'Rejected leave'), ('PERSON_CREATED', 'Added a person'), ('PERSON_UPDATED', 'Changed a person'), ('PERSON_DEACTIVATED', 'Deactivated a person'), ('PERSON_REACTIVATED', 'Reactivated a person'), ('ROLE_CHANGED', 'Changed a role'), ('INVITATION_SENT', 'Sent a link to set a password'), ('SETTINGS_CHANGED', 'Changed company settings'), ('RULES_CHANGED', 'Changed working time rules'), ('APPLICATION_CREATED', 'Registered an application'), ('APPLICATION_REVOKED', 'Revoked an application credential'), ('METADATA_PURGED', 'Purged security metadata')], db_index=True, max_length=32, verbose_name='action'),
        ),
    ]
