# Generated by Django 6.1 on 2026-08-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_alter_auditlog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='ip_address',
        ),
    ]
