# Generated by Django 6.1 on 2026-08-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0013_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('RECORD_VIEWED', "Read somebody else's record"), ('REPORT_EXPORTED', 'Exported a working time report'), ('DOCUMENT_DOWNLOADED', 'Downloaded a supporting document'), ('CORRECTION_REQUESTED', 'Requested a correction'), ('CORRECTION_APPROVED', 'Approved a correction'), ('CORRECTION_REJECTED', 'Rejected a correction'), ('PUNCH_VOIDED', 'Voided a clock event'), ('CORRECTION_DISPUTED', 'Disagreed with a proposed change'), ('CORRECTION_IMPOSED', 'Applied a change without agreement'), ('CORRECTION_WITHDRAWN', 'Withdrew a proposed change'), ('ABSENCE_APPROVED', 'Approved leave'), ('ABSENCE_REJECTED', 'Rejected leave'), ('ABSENCE_CANCELLED', 'Cancelled a leave request'), ('OVERTIME_AUTHORISED', 'Authorised overtime'), ('OVERTIME_REJECTED', 'Did not authorise overtime'), ('HOLIDAY_RECOVERY_CONFIRMED', 'Confirmed holiday recovered from sick leave'), ('HOLIDAY_RECOVERY_DISMISSED', 'Dismissed a holiday recovery'), ('PERSON_CREATED', 'Added a person'), ('PERSON_UPDATED', 'Changed a person'), ('PERSON_DEACTIVATED', 'Deactivated a person'), ('PERSON_REACTIVATED', 'Reactivated a person'), ('ROLE_CHANGED', 'Changed a role'), ('SHIFT_REASSIGNED', 'Moved a shift to somebody else'), ('SHIFTS_ASSIGNED', 'Painted shifts over a period'), ('SHIFTS_CLEARED', 'Cleared shifts over a period'), ('LEAVE_TYPE_CHANGED', 'Changed what a leave grants'), ('STRUCTURE_CHANGED', 'Changed the structure or the calendar'), ('INVITATION_SENT', 'Sent a link to set a password'), ('SETTINGS_CHANGED', 'Changed company settings'), ('RULES_CHANGED', 'Changed working time rules'), ('APPLICATION_CREATED', 'Registered an application'), ('APPLICATION_REVOKED', 'Revoked an application credential'), ('METADATA_PURGED', 'Purged security metadata'), ('RECORD_PURGED', 'Purged expired working time records')], db_index=True, max_length=32, verbose_name='action'),
        ),
    ]
