# Generated by Django 6.1 on 2026-09-23 06:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0020_alter_auditlog_action'),
        ('tenants', '0036_tenant_offline_punch_grace_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='when')),
                ('actor_label', models.CharField(blank=True, max_length=160, verbose_name='who (as recorded)')),
                ('action', models.CharField(choices=[('COMPANY_CREATED', 'Created a company'), ('IDENTITY_CHANGED', "Changed how a company's people sign in"), ('APPLICATION_AUTHORISED', 'Authorised an application'), ('APPLICATION_CHANGED', "Changed an application's permissions"), ('APPLICATION_WITHDRAWN', 'Withdrew an application'), ('CREDENTIAL_ISSUED', 'Issued a credential'), ('CREDENTIAL_REVOKED', 'Revoked a credential'), ('ADMIN_CREATED', 'Created an installation account'), ('ADMIN_PASSWORD_RESET', 'Gave an installation account a new password'), ('ADMIN_DEACTIVATED', 'Deactivated an installation account')], db_index=True, max_length=32, verbose_name='action')),
                ('company_label', models.CharField(blank=True, max_length=255, verbose_name='company (as recorded)')),
                ('target_type', models.CharField(blank=True, max_length=32, verbose_name='type')),
                ('target_id', models.UUIDField(blank=True, null=True, verbose_name='identifier')),
                ('target_label', models.CharField(blank=True, max_length=200, verbose_name='what (as recorded)')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='changes')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='note')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='who')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='platform_audit_entries', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'installation audit entry',
                'verbose_name_plural': 'installation audit trail',
                'ordering': ['-at'],
            },
        ),
    ]
