# Generated by Django 6.1 on 2026-09-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0024_company_admin_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformauditentry',
            name='action',
            field=models.CharField(choices=[('COMPANY_CREATED', 'Created a company'), ('COMPANY_CHANGED', "Changed a company's details"), ('COMPANY_DEACTIVATED', 'Deactivated a company'), ('COMPANY_REACTIVATED', 'Reactivated a company'), ('COMPANY_ADMIN_LINK_SENT', 'Sent a company administrator a link to set a password'), ('IDENTITY_CHANGED', "Changed how a company's people sign in"), ('APPLICATION_AUTHORISED', 'Authorised an application'), ('APPLICATION_CHANGED', "Changed an application's permissions"), ('APPLICATION_WITHDRAWN', 'Withdrew an application'), ('CREDENTIAL_ISSUED', 'Issued a credential'), ('CREDENTIAL_REVOKED', 'Revoked a credential'), ('ADMIN_CREATED', 'Created an installation account'), ('ADMIN_PASSWORD_RESET', 'Gave an installation account a new password'), ('ADMIN_DEACTIVATED', 'Deactivated an installation account'), ('ADMIN_CHANGED', 'Changed an installation account'), ('ADMIN_REACTIVATED', 'Reactivated an installation account'), ('ADMIN_LINK_SENT', 'Sent an installation account a link to set a password')], db_index=True, max_length=32, verbose_name='action'),
        ),
    ]
