# Generated by Django 6.1 on 2026-09-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0025_installation_account_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('RECORD_VIEWED', "Read somebody else's record"), ('REPORT_EXPORTED', 'Exported a working time report'), ('DOCUMENT_DOWNLOADED', 'Downloaded a supporting document'), ('CORRECTION_REQUESTED', 'Requested a correction'), ('CORRECTION_APPROVED', 'Approved a correction'), ('CORRECTION_REJECTED', 'Rejected a correction'), ('PUNCH_VOIDED', 'Voided a clock event'), ('CORRECTION_DISPUTED', 'Disagreed with a proposed change'), ('CORRECTION_IMPOSED', 'Applied a change without agreement'), ('CORRECTION_WITHDRAWN', 'Withdrew a proposed change'), ('ABSENCE_REQUESTED', 'Requested leave'), ('ABSENCE_APPROVED', 'Approved leave'), ('ABSENCE_REJECTED', 'Rejected leave'), ('ABSENCE_CANCELLED', 'Cancelled a leave request'), ('OVERTIME_AUTHORISED', 'Authorised overtime'), ('OVERTIME_REJECTED', 'Did not authorise overtime'), ('HOLIDAY_RECOVERY_CONFIRMED', 'Confirmed holiday recovered from sick leave'), ('HOLIDAY_RECOVERY_DISMISSED', 'Dismissed a holiday recovery'), ('PERSON_CREATED', 'Added a person'), ('PERSON_UPDATED', 'Changed a person'), ('PERSON_DEACTIVATED', 'Deactivated a person'), ('PERSON_REACTIVATED', 'Reactivated a person'), ('ROLE_CHANGED', 'Changed a role'), ('SHIFT_REASSIGNED', 'Moved a shift to somebody else'), ('SHIFTS_ASSIGNED', 'Painted shifts over a period'), ('SHIFTS_CLEARED', 'Cleared shifts over a period'), ('LEAVE_TYPE_CHANGED', 'Changed what a leave grants'), ('STRUCTURE_CHANGED', 'Changed the structure or the calendar'), ('INVITATION_SENT', 'Sent a link to set a password'), ('SETTINGS_CHANGED', 'Changed company settings'), ('RULES_CHANGED', 'Changed working time rules'), ('APPLICATION_CREATED', 'Registered an application'), ('APPLICATION_REVOKED', 'Revoked an application credential'), ('APPLICATION_ACTED_AS', 'Obtained a session for a person'), ('SESSIONS_ENDED', "Ended somebody's sessions"), ('IDENTITY_CHANGED', 'Changed how people sign in'), ('METADATA_PURGED', 'Purged security metadata'), ('RECORD_PURGED', 'Purged expired working time records'), ('RECORD_DELIVERED', 'Delivered somebody their own record'), ('PERSON_ERASED', 'Erased a person who left no record'), ('SUPPORT_ENTERED', 'Support entered the company')], db_index=True, max_length=32, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='platformauditentry',
            name='action',
            field=models.CharField(choices=[('COMPANY_CREATED', 'Created a company'), ('COMPANY_CHANGED', "Changed a company's details"), ('COMPANY_DEACTIVATED', 'Deactivated a company'), ('COMPANY_REACTIVATED', 'Reactivated a company'), ('COMPANY_ADMIN_LINK_SENT', 'Sent a company administrator a link to set a password'), ('IDENTITY_CHANGED', "Changed how a company's people sign in"), ('APPLICATION_AUTHORISED', 'Authorised an application'), ('APPLICATION_CHANGED', "Changed an application's permissions"), ('APPLICATION_WITHDRAWN', 'Withdrew an application'), ('CREDENTIAL_ISSUED', 'Issued a credential'), ('CREDENTIAL_REVOKED', 'Revoked a credential'), ('ADMIN_CREATED', 'Created an installation account'), ('ADMIN_PASSWORD_RESET', 'Gave an installation account a new password'), ('ADMIN_DEACTIVATED', 'Deactivated an installation account'), ('ADMIN_CHANGED', 'Changed an installation account'), ('ADMIN_REACTIVATED', 'Reactivated an installation account'), ('ADMIN_LINK_SENT', 'Sent an installation account a link to set a password'), ('SUPPORT_ENTERED', 'Entered a company as support')], db_index=True, max_length=32, verbose_name='action'),
        ),
    ]
