# Generated by Django 6.1 on 2026-08-11 20:09

import apps.shifts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0006_workingtimerules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('segments', models.JSONField(help_text='For example: [{"start": "09:00", "end": "13:00"}, {"start": "15:00", "end": "19:00"}] for a split day.', validators=[apps.shifts.models.validate_segments], verbose_name='time spans')),
                ('colour', models.CharField(default='#1b5e4a', help_text='Hex, for the roster. Never the only way a shift is identified.', max_length=7, verbose_name='colour')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'shift pattern',
                'verbose_name_plural': 'shift patterns',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('day', models.DateField(verbose_name='day')),
                ('segments', models.JSONField(validators=[apps.shifts.models.validate_segments], verbose_name='time spans')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='shifts.shiftpattern', verbose_name='pattern')),
            ],
            options={
                'verbose_name': 'shift',
                'verbose_name_plural': 'shifts',
                'ordering': ['day'],
            },
        ),
        migrations.AddConstraint(
            model_name='shiftpattern',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='shift_pattern_name_unique_per_company'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['tenant', 'day'], name='shifts_shif_tenant__ec322b_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['employee', 'day'], name='shifts_shif_employe_371938_idx'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('employee', 'day'), name='one_shift_per_person_per_day'),
        ),
    ]
