# Generated by Django 6.1 on 2026-08-11 20:19

import apps.shifts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftpattern',
            name='segments',
            field=models.JSONField(help_text='Pairs of start and end times. Two of them make a split day.', validators=[apps.shifts.models.validate_segments], verbose_name='time spans'),
        ),
    ]
