"""The summary that goes out with the payslip (art. 6.1).

    «Sin perjuicio de lo anterior, la empresa entregará, junto con el recibo de
    salarios, copia del resumen correspondiente al periodo fijado para el abono
    de las retribuciones.»

Three things follow from that sentence, and each one shaped something here.

**«junto con el recibo de salarios»** means this is not the same document as
the inspection report. It accompanies a payslip, so it covers the pay period
and it is meant to be read by the person, not by an inspector reconciling
entries. Same data, different reader.

**«el periodo fijado para el abono»** is not necessarily a calendar month. Most
of Spain pays monthly, some sectors pay fortnightly or weekly, and hardcoding
the month would quietly produce a summary covering the wrong days.

**«entregará»** is an obligation to hand over, not to make available. The
system cannot post a letter, but it can record that the summary was generated
and for whom --- so the company can show it did, and can see who is missing.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, timedelta

from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.common.models import TenantOwnedModel


class PayrollPeriod(models.TextChoices):
    """How often the company pays. Art. 29.1 ET caps the interval at a month."""

    MONTHLY = "MONTHLY", _("Monthly")
    FORTNIGHTLY = "FORTNIGHTLY", _("Every two weeks")
    WEEKLY = "WEEKLY", _("Weekly")


@dataclass(frozen=True)
class Period:
    first: date
    last: date
    label: str


def period_containing(day: date, kind: str) -> Period:
    """The pay period a day falls in.

    Weekly runs Monday to Sunday, and fortnightly splits the month at the 15th
    rather than counting fourteen days from an arbitrary origin --- which is how
    companies that pay twice a month actually do it, and drifting weeks would
    put the same day in different periods depending on when you asked.
    """
    if kind == PayrollPeriod.WEEKLY:
        monday = day - timedelta(days=day.weekday())
        sunday = monday + timedelta(days=6)
        return Period(monday, sunday, f"{monday:%d/%m} - {sunday:%d/%m/%Y}")

    if kind == PayrollPeriod.FORTNIGHTLY:
        if day.day <= 15:
            first, last = day.replace(day=1), day.replace(day=15)
        else:
            first = day.replace(day=16)
            last = _last_day_of_month(day)
        return Period(first, last, f"{first:%d/%m} - {last:%d/%m/%Y}")

    first = day.replace(day=1)
    last = _last_day_of_month(day)
    return Period(first, last, f"{first:%B %Y}")


def _last_day_of_month(day: date) -> date:
    following = day.replace(day=28) + timedelta(days=4)
    return following - timedelta(days=following.day)


class PayrollSummary(TenantOwnedModel):
    """Proof that the summary for a period was produced for a person.

    Kept because «entregará» is an obligation the company has to be able to
    evidence. Without a record of it, the only answer to "did you hand it over"
    is somebody's memory.

    It stores the fingerprint of the document, not the document: regenerating
    the same period yields the same figures, and keeping a copy of every
    payslip-adjacent summary for four years would multiply the storage for
    something reproducible. If the two ever differ, the fingerprint says so.
    """

    employee = models.ForeignKey(
        "users.User",
        on_delete=models.CASCADE,
        related_name="payroll_summaries",
        verbose_name=_("employee"),
    )
    period_start = models.DateField(_("from"))
    period_end = models.DateField(_("to"))

    total_seconds = models.PositiveIntegerField(_("hours in the period"), default=0)
    overtime_seconds = models.PositiveIntegerField(_("overtime in the period"), default=0)
    fingerprint = models.CharField(_("document fingerprint"), max_length=64)

    generated_by = models.ForeignKey(
        "users.User",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="payroll_summaries_generated",
        verbose_name=_("generated by"),
    )

    class Meta:
        verbose_name = _("payroll summary")
        verbose_name_plural = _("payroll summaries")
        ordering = ["-period_end", "employee"]
        constraints = [
            # One per person per period. Regenerating it is fine --- the figures
            # are reproducible --- but two rows for the same period would make
            # "was it handed over" ambiguous, which is the one question this
            # table exists to answer.
            models.UniqueConstraint(
                fields=["employee", "period_start", "period_end"],
                name="one_payroll_summary_per_person_and_period",
            )
        ]

    def __str__(self) -> str:
        return f"{self.employee_id} {self.period_start} - {self.period_end}"
