"""Report endpoints: the legal output of the product."""

from __future__ import annotations

from datetime import date, timedelta

from django.http import HttpResponse
from django.utils.translation import gettext as _
from drf_spectacular.utils import OpenApiParameter, extend_schema
from rest_framework import status
from rest_framework.exceptions import ValidationError
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.audit.models import AuditAction
from apps.audit.services import record
from apps.common.exceptions import BusinessRuleError
from apps.common.permissions import IsAuthenticatedInTenant
from apps.reports.payroll import PayrollSummary, period_containing
from apps.reports.pdf import render_pdf
from apps.reports.renderers import CSVRenderer, PDFRenderer
from apps.reports.services import build_report, to_csv
from apps.users.models import User


def _parse_date(value: str | None, fallback: date) -> date:
    if not value:
        return fallback
    try:
        return date.fromisoformat(value)
    except ValueError as exc:
        raise ValidationError({"detail": _("Dates must be written as YYYY-MM-DD.")}) from exc


@extend_schema(
    tags=["reports"],
    summary="Working time report",
    description=(
        "Produces the record required by Article 34.9: company, employee, daily entries "
        "and exits, totals and a verification hash. A worker may request their own; a "
        "manager or administrator may request anyone's in the company."
    ),
    parameters=[
        OpenApiParameter("employee", str, description="Employee id. Defaults to the caller."),
        OpenApiParameter("date_from", str, description="YYYY-MM-DD. Defaults to 30 days ago."),
        OpenApiParameter("date_to", str, description="YYYY-MM-DD. Defaults to today."),
        OpenApiParameter("format", str, enum=["pdf", "csv"], description="Defaults to pdf."),
    ],
    responses={200: None},
)
class ReportView(APIView):
    permission_classes = [IsAuthenticatedInTenant]
    # Declared so `?format=pdf` and `?format=csv` are understood as content
    # negotiation. Without them DRF answers 404 to a format it does not know.
    renderer_classes = [PDFRenderer, CSVRenderer]

    def get(self, request):
        company = request.user.tenant
        today = date.today()

        date_from = _parse_date(request.query_params.get("date_from"), today - timedelta(days=30))
        date_to = _parse_date(request.query_params.get("date_to"), today)
        if date_to < date_from:
            raise ValidationError({"detail": _("The end date cannot precede the start date.")})

        employee = request.user
        requested = request.query_params.get("employee")
        if requested and str(requested) != str(request.user.id):
            # Asking for somebody else's record requires a management role. The
            # lookup is scoped to the company, so an id from elsewhere is a 404.
            if not request.user.can_manage:
                raise ValidationError({"detail": _("You may only request your own record.")})
            employee = User.objects.filter(tenant=company, pk=requested).first()
            if employee is None:
                raise ValidationError({"detail": _("That person does not exist.")})

        data = build_report(
            employee=employee, company=company, date_from=date_from, date_to=date_to
        )

        stem = f"working-time_{employee.last_name}_{date_from}_{date_to}".replace(" ", "-")

        if request.query_params.get("format", "pdf").lower() == "csv":
            response = HttpResponse(to_csv(data), content_type="text/csv; charset=utf-8")
            response["Content-Disposition"] = f'attachment; filename="{stem}.csv"'
        else:
            response = HttpResponse(render_pdf(data), content_type="application/pdf")
            response["Content-Disposition"] = f'attachment; filename="{stem}.pdf"'

        # Also as a header, so an automated consumer can check it without
        # opening the document.
        response["X-Report-Hash"] = data.fingerprint

        # Exporting somebody else's record is exactly the kind of thing an
        # inspection --- or the person concerned --- may later ask about.
        if employee.id != request.user.id:
            record(
                action=AuditAction.REPORT_EXPORTED,
                actor=request.user,
                target=employee,
                target_type="user",
                target_label=employee.get_full_name(),
                changes={"from": str(date_from), "to": str(date_to)},
                note=f"hash {data.fingerprint[:16]}",
                request=request,
            )
        return response


@extend_schema(tags=["reports"])
class PayrollSummaryView(APIView):
    """The summary that goes out with the payslip (art. 6.1).

    Read for the person concerned, generated by whoever runs the payroll. The
    period comes from the company's own pay cycle rather than from the caller,
    because the article ties it to «el periodo fijado para el abono» and letting
    a request pick its own dates would produce summaries that match no payslip.
    """

    permission_classes = [IsAuthenticatedInTenant]
    # Declared so `?format=pdf` and `?format=csv` are read as content
    # negotiation. Without them DRF answers 404 to a format it does not know ---
    # the same trap the inspection report fell into.
    renderer_classes = [JSONRenderer, PDFRenderer, CSVRenderer]

    @extend_schema(
        parameters=[
            OpenApiParameter("employee", str, description="Defaults to the caller."),
            OpenApiParameter(
                "day", str, description="Any day inside the period. Defaults to today."
            ),
            OpenApiParameter("format", str, enum=["json", "pdf", "csv"]),
        ],
        responses={200: None},
    )
    def get(self, request):
        company = request.user.tenant
        employee = _employee_for(request)

        anchor = _parse_date(request.query_params.get("day"), date.today())
        period = period_containing(anchor, company.payroll_period)

        data = build_report(
            employee=employee,
            company=company,
            date_from=period.first,
            date_to=period.last,
        )

        wanted = request.query_params.get("format", "json").lower()
        if wanted in {"pdf", "csv"}:
            return _as_file(data, wanted, employee, period)

        return Response(
            {
                "employee": str(employee.id),
                "employee_name": employee.get_full_name(),
                "period": {
                    "from": period.first.isoformat(),
                    "to": period.last.isoformat(),
                    "label": period.label,
                },
                "total_seconds": data.total_seconds,
                "overtime_seconds": data.total_overtime_seconds,
                "break_seconds": data.total_break_seconds,
                "days": len([r for r in data.rows if r.seconds or r.absence]),
                "fingerprint": data.fingerprint,
                "part_time": data.part_time,
                "contracted_schedule": data.contracted_schedule,
            }
        )

    @extend_schema(request=None, responses={201: dict})
    def post(self, request):
        """Generates the period's summaries for the whole company, and records it.

        Bulk because that is how payroll happens: nobody produces these one at a
        time on the day the payslips go out. Recording it because «entregará» is
        an obligation the company has to be able to evidence --- and because the
        response says who is missing, which is the question somebody running
        payroll actually has.
        """
        if not request.user.can_manage:
            raise BusinessRuleError(
                code="not_allowed",
                message=_("Only a manager or an administrator generates the summaries."),
            )

        company = request.user.tenant
        anchor = _parse_date(request.data.get("day"), date.today())
        period = period_containing(anchor, company.payroll_period)

        made, skipped = [], []
        for person in User.objects.filter(tenant=company, is_active=True):
            data = build_report(
                employee=person,
                company=company,
                date_from=period.first,
                date_to=period.last,
            )
            if data.total_seconds == 0:
                # Nothing worked in the period. No summary rather than a page of
                # zeros: a payslip with no hours behind it invites the question
                # of whether the record failed or the person did not work.
                skipped.append(person.get_full_name() or person.email)
                continue

            PayrollSummary.objects.update_or_create(
                employee=person,
                period_start=period.first,
                period_end=period.last,
                defaults={
                    "tenant": company,
                    "total_seconds": data.total_seconds,
                    "overtime_seconds": data.total_overtime_seconds,
                    "fingerprint": data.fingerprint,
                    "generated_by": request.user,
                },
            )
            made.append(person.get_full_name() or person.email)

        return Response(
            {
                "period": {"from": period.first.isoformat(), "to": period.last.isoformat()},
                "generated": len(made),
                "without_hours": skipped,
            },
            status=status.HTTP_201_CREATED,
        )


def _employee_for(request):
    wanted = request.query_params.get("employee")
    if not wanted or wanted == str(request.user.id):
        return request.user
    if not request.user.can_manage:
        raise BusinessRuleError(
            code="not_your_summary",
            message=_("You may only ask for your own summary."),
        )
    person = User.objects.filter(tenant=request.user.tenant, pk=wanted).first()
    if person is None:
        raise BusinessRuleError(
            code="unknown_employee", message=_("That person is not in this company.")
        )
    return person


def _as_file(data, wanted, employee, period):
    stem = f"resumen_{employee.last_name}_{period.first}_{period.last}".replace(" ", "-")
    if wanted == "csv":
        response = HttpResponse(to_csv(data), content_type="text/csv; charset=utf-8")
        response["Content-Disposition"] = f'attachment; filename="{stem}.csv"'
    else:
        response = HttpResponse(render_pdf(data), content_type="application/pdf")
        response["Content-Disposition"] = f'attachment; filename="{stem}.pdf"'
    response["X-Report-Hash"] = data.fingerprint
    return response
