# Generated by Django 6.1 on 2026-08-11 14:51

import apps.tenants.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, verbose_name='legal name')),
                ('tax_id', models.CharField(help_text='Company tax number (CIF/NIF, VAT, EIN…).', max_length=32, unique=True, verbose_name='tax identifier')),
                ('country', models.CharField(default='ES', help_text='ISO 3166-1 alpha-2 code. Selects the applicable legal rules.', max_length=2, verbose_name='country')),
                ('time_zone', models.CharField(default=apps.tenants.models.default_time_zone, help_text='IANA name. Storage is always UTC; this only affects display.', max_length=64, validators=[apps.tenants.models.validate_time_zone], verbose_name='time zone')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='settings')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantLimits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('max_employees', models.IntegerField(blank=True, null=True, verbose_name='maximum employees')),
                ('max_admins', models.IntegerField(blank=True, null=True, verbose_name='maximum administrators')),
                ('max_storage_mb', models.IntegerField(blank=True, null=True, verbose_name='maximum storage (MB)')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='enabled features')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'company limits',
                'verbose_name_plural': 'company limits',
            },
        ),
    ]
