# Generated by Django 6.1 on 2026-08-11 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('scopes', models.JSONField(default=list, help_text='List of granted scopes. Empty means the application can do nothing.', verbose_name='permissions')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_created', to=settings.AUTH_USER_MODEL, verbose_name='authorised by')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='label')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='token hash')),
                ('token_hint', models.CharField(editable=False, help_text='Last characters, to tell one credential from another in the interface.', max_length=16, verbose_name='hint')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='tenants.application', verbose_name='application')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'application credential',
                'verbose_name_plural': 'application credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_application_per_company'),
        ),
    ]
