# Generated by Django 6.1 on 2026-08-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_application_applicationcredential_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='record_retention_years',
            field=models.PositiveSmallIntegerField(default=4, help_text='How long clock events are kept. Four years is the floor set by art. 34.9 ET; a longer period needs its own justification, since keeping data because it might be useful is not a basis.', verbose_name='record retention (years)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='security_metadata_retention_days',
            field=models.PositiveSmallIntegerField(default=365, help_text='How long the IP address, device and user agent of each event are kept. They serve to spot anomalies, not to prove working time: purging them leaves the record intact.', verbose_name='security metadata retention (days)'),
        ),
    ]
