# Generated by Django 6.1 on 2026-08-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_record_retention_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='annual_leave_days',
            field=models.PositiveSmallIntegerField(default=22, help_text='Working days of holiday per reference period. Art. 38 ET sets a floor of 30 calendar days; the agreement may give more. An individual employee can be given a different figure.', verbose_name='annual leave days'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='leave_year_start_month',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1, help_text='Month the holiday reference period begins. 1 = calendar year. The period is not necessarily the calendar year: the agreement decides.', verbose_name='reference period starts in'),
        ),
    ]
