# Generated by Django 6.1 on 2026-08-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_annual_leave_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English'), ('ca', 'Catalan'), ('gl', 'Galician'), ('eu', 'Basque'), ('fr', 'French'), ('pt', 'Portuguese'), ('de', 'German')], default='es', help_text="Language the company works in. A person can override it for themselves; the browser's setting is only used when neither is set.", max_length=10, verbose_name='language'),
        ),
    ]
