# Generated by Django 6.1 on 2026-08-11 20:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingTimeRules',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('weekly_hours', models.DecimalField(decimal_places=1, default=40, help_text='Art. 34.1 ET: 40 hours a week on average over the reference period. An ordinary legal maximum; the agreement or the contract may improve it.', max_digits=4, verbose_name='weekly hours')),
                ('daily_rest_hours', models.PositiveSmallIntegerField(default=12, help_text='Art. 34.3 ET. RD 1561/1995 modifies it for particular sectors, which is why departing from it is reported and not prevented.', verbose_name='rest between working days (hours)')),
                ('weekly_rest_hours', models.PositiveSmallIntegerField(default=36, help_text='Art. 37.1 ET: a day and a half uninterrupted. It may be accumulated over periods of up to fourteen days.', verbose_name='weekly rest (hours)')),
                ('break_after_hours', models.DecimalField(decimal_places=1, default=6, help_text='Art. 34.4 ET: fifteen minutes when the continuous day exceeds six hours.', max_digits=3, verbose_name='a continuous day needs a break after (hours)')),
                ('break_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='break (minutes)')),
                ('break_counts_as_work', models.BooleanField(default=False, help_text='Only when the agreement or the contract says so. Assuming it would overstate the hours worked.', verbose_name='the break counts as working time')),
                ('annual_overtime_hours', models.PositiveSmallIntegerField(default=80, help_text='Art. 35.2 ET.', verbose_name='overtime hours per year')),
                ('night_starts_at', models.TimeField(default='22:00', help_text='Art. 36.1 ET: between 22:00 and 06:00.', verbose_name='night work starts at')),
                ('night_ends_at', models.TimeField(default='06:00', verbose_name='night work ends at')),
                ('roster_notice_days', models.PositiveSmallIntegerField(default=5, help_text="Art. 34.2 ET requires five days' notice for irregular distribution of the working day. Art. 38.3 ET asks for the holiday calendar two months ahead.", verbose_name='notice for roster changes (days)')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_time_rules', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'working time rules',
                'verbose_name_plural': 'working time rules',
            },
        ),
    ]
