# Generated by Django 6.1 on 2026-08-12 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_workingtimerules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtimerules',
            name='night_ends_at',
            field=models.TimeField(default=datetime.time(6, 0), verbose_name='night work ends at'),
        ),
        migrations.AlterField(
            model_name='workingtimerules',
            name='night_starts_at',
            field=models.TimeField(default=datetime.time(22, 0), help_text='Art. 36.1 ET: between 22:00 and 06:00.', verbose_name='night work starts at'),
        ),
    ]
