# Generated by Django 6.1 on 2026-08-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_workingtimerules_night_ends_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtimerules',
            name='correction_consent_days',
            field=models.PositiveSmallIntegerField(default=7, help_text="Art. 4.b needs the person's authorisation to change an entry but sets no deadline for answering. Without one a proposal would hang forever, so the company sets the window. Past it the change can be applied, recorded as made without agreement.", verbose_name='days to answer a proposed correction'),
        ),
    ]
