# Generated by Django 6.1 on 2026-08-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_workingtimerules_correction_consent_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='payroll_period',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('FORTNIGHTLY', 'Every two weeks'), ('WEEKLY', 'Weekly')], default='MONTHLY', help_text='Art. 6.1: a copy of the summary for this period goes out with the payslip. Not necessarily a calendar month --- art. 29.1 ET only caps the interval at one.', max_length=16, verbose_name='pay period'),
        ),
    ]
