# Generated by Django 6.1 on 2026-08-12 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenant_payroll_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtimerules',
            name='annual_overtime_hours',
            field=models.PositiveSmallIntegerField(default=80, help_text='Overtime hours allowed per year.', verbose_name='overtime hours per year'),
        ),
        migrations.AlterField(
            model_name='workingtimerules',
            name='break_after_hours',
            field=models.DecimalField(decimal_places=1, default=6, help_text='A continuous day longer than this is owed a break.', max_digits=3, verbose_name='a continuous day needs a break after (hours)'),
        ),
        migrations.AlterField(
            model_name='workingtimerules',
            name='correction_consent_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Days to answer a proposed change before the company may apply it anyway, recorded as made without agreement.', verbose_name='days to answer a proposed correction'),
        ),
        migrations.AlterField(
            model_name='workingtimerules',
            name='daily_rest_hours',
            field=models.PositiveSmallIntegerField(default=12, help_text='Hours between the end of a working day and the start of the next.', verbose_name='rest between working days (hours)'),
        ),
        migrations.AlterField(
            model_name='workingtimerules',
            name='night_starts_at',
            field=models.TimeField(default=datetime.time(22, 0), help_text='Start of the night window.', verbose_name='night work starts at'),
        ),
        migrations.AlterField(
            model_name='workingtimerules',
            name='roster_notice_days',
            field=models.PositiveSmallIntegerField(default=5, help_text='Days of notice before a roster change.', verbose_name='notice for roster changes (days)'),
        ),
        migrations.AlterField(
            model_name='workingtimerules',
            name='weekly_hours',
            field=models.DecimalField(decimal_places=1, default=40, help_text='Hours a week. See the citation served with the rules.', max_digits=4, verbose_name='weekly hours'),
        ),
        migrations.AlterField(
            model_name='workingtimerules',
            name='weekly_rest_hours',
            field=models.PositiveSmallIntegerField(default=36, help_text='Uninterrupted hours of weekly rest.', verbose_name='weekly rest (hours)'),
        ),
    ]
