# Generated by Django 6.1 on 2026-08-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_rules_help_text_moved_to_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtimerules',
            name='complementary_hours_share',
            field=models.PositiveSmallIntegerField(default=30, help_text='Cap on hours a part-time contract may work beyond what was agreed, as a percentage of it.', verbose_name='complementary hours, max % of the contract'),
        ),
    ]
