# Generated by Django 6.1 on 2026-08-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_complementary_hours_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtimerules',
            name='complementary_hours_share',
            field=models.PositiveSmallIntegerField(default=30, help_text='Cap on hours a part-time contract may work beyond what was agreed, as a percentage of it.', verbose_name='complementary hours, share of the contract (%)'),
        ),
    ]
