# Generated by Django 6.1 on 2026-08-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_alter_workingtimerules_complementary_hours_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='leave_days_are_working_days',
            field=models.BooleanField(default=True, help_text='On: only the days the person was due to work are deducted, so a fortnight off costs ten. Off: every day between the two dates is deducted, weekends included, and the figure above should be the calendar-day one from the agreement.', verbose_name='counted in working days'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='annual_leave_days',
            field=models.PositiveSmallIntegerField(default=22, help_text='Days of holiday per reference period, in the unit chosen below. Art. 38 ET sets a floor of 30 calendar days, which is 22 working days on a five-day week; the agreement may give more. An individual employee can be given a different figure.', verbose_name='annual leave days'),
        ),
    ]
