# Generated by Django 6.1 on 2026-08-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_tenant_leave_days_are_working_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='managers_see_whole_company',
            field=models.BooleanField(default=False, help_text='Off: a manager reads and resolves only for the departments they were put in charge of. On: for everybody, which is what a company small enough not to have departments wants.', verbose_name='managers see the whole company'),
        ),
    ]
