# Generated by Django 6.1 on 2026-08-12 20:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_tenant_managers_see_whole_company'),
        ('users', '0011_workplace_user_workplace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('day', models.DateField(verbose_name='day')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('scope', models.CharField(choices=[('NATIONAL', 'National'), ('REGIONAL', 'Regional'), ('LOCAL', 'Local'), ('COMPANY', 'Company')], default='LOCAL', max_length=10, verbose_name='origin')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
                ('workplace', models.ForeignKey(blank=True, help_text='Empty applies it to the whole company.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='users.workplace', verbose_name='workplace')),
            ],
            options={
                'verbose_name': 'public holiday',
                'verbose_name_plural': 'public holidays',
                'ordering': ['day'],
                'indexes': [models.Index(fields=['tenant', 'day'], name='tenants_pub_tenant__37c1bc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('workplace__isnull', True)), fields=('tenant', 'day'), name='one_company_holiday_per_day'), models.UniqueConstraint(condition=models.Q(('workplace__isnull', False)), fields=('tenant', 'day', 'workplace'), name='one_workplace_holiday_per_day')],
            },
        ),
    ]
