# Generated by Django 6.1 on 2026-08-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_publicholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtimerules',
            name='entry_tolerance_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='A punch within this many minutes of the rostered start counts as on time. 0 is strict.', verbose_name='entry tolerance (minutes)'),
        ),
        migrations.AddField(
            model_name='workingtimerules',
            name='exit_tolerance_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Leaving within this many minutes of the rostered end is not early.', verbose_name='exit tolerance (minutes)'),
        ),
    ]
