# Generated by Django 6.1 on 2026-08-13 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_workingtimerules_entry_tolerance_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtimerules',
            name='quiet_from',
            field=models.TimeField(default=datetime.time(21, 0), help_text='Art. 88 LOPDGDD: the right to disconnect. Nothing is sent after this.', verbose_name='no notifications from'),
        ),
        migrations.AddField(
            model_name='workingtimerules',
            name='quiet_until',
            field=models.TimeField(default=datetime.time(7, 0), help_text='Nothing is sent before this either.', verbose_name='no notifications until'),
        ),
    ]
