# Generated by Django 6.1 on 2026-08-13 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_workingtimerules_quiet_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(blank=True, choices=[('COLLECTIVE', 'collective agreement'), ('COMPANY', 'company-level agreement'), ('EMPLOYER', 'employer decision after consulting the representatives')], help_text='Art. 34.9 ET. Empty means it has not been declared yet.', max_length=12, verbose_name='how it was organised')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='which one')),
                ('in_force_since', models.DateField(blank=True, null=True, verbose_name='in force since')),
                ('consulted_on', models.DateField(blank=True, null=True, verbose_name='representatives consulted on')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record_arrangement', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'record arrangement',
                'verbose_name_plural': 'record arrangements',
            },
        ),
    ]
