# Generated by Django 6.1 on 2026-08-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_recordarrangement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('ca', 'Catalan'), ('gl', 'Galician'), ('en', 'English')], default='es', help_text="Language the company works in. A person can override it for themselves; the browser's setting is only used when neither is set.", max_length=10, verbose_name='language'),
        ),
    ]
