# Generated by Django 6.1 on 2026-08-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_alter_tenant_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtimerules',
            name='max_open_hours',
            field=models.PositiveSmallIntegerField(default=16, help_text='After this, an unclosed working day is read as a forgotten clock-out rather than a shift still running. Raise it for 24-hour on-call rosters.', verbose_name='longest a working day may stay open (hours)'),
        ),
    ]
