# Generated by Django 6.1 on 2026-08-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_workingtimerules_max_open_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantlimits',
            name='max_admins',
        ),
        migrations.RemoveField(
            model_name='tenantlimits',
            name='max_employees',
        ),
        migrations.RemoveField(
            model_name='tenantlimits',
            name='max_storage_mb',
        ),
    ]
