# Generated by Django 6.1 on 2026-08-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0021_remove_tenantlimits_max_admins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='record_retention_years',
            field=models.PositiveSmallIntegerField(default=4, help_text='How long clock events are kept. Four years is the floor set by art. 34.9 ET; a longer period needs its own justification, since keeping data because it might be useful is not a basis. Note that nothing is deleted automatically yet: this states the policy, it does not enforce it.', verbose_name='record retention (years)'),
        ),
    ]
