# Generated by Django 6.1 on 2026-08-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0022_alter_tenant_record_retention_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtimerules',
            name='from_agreement',
            field=models.JSONField(blank=True, default=dict, verbose_name='figures taken from an agreement'),
        ),
    ]
