# Generated by Django 6.1 on 2026-08-26 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0023_workingtimerules_from_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtimerules',
            name='max_open_hours',
            field=models.PositiveSmallIntegerField(default=16, help_text='After this, an unclosed working day is read as a forgotten clock-out rather than a shift still running. Raise it for 24-hour on-call rosters.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='longest a working day may stay open (hours)'),
        ),
    ]
