# Generated by Django 6.1 on 2026-08-26 19:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0024_alter_workingtimerules_max_open_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputationRuleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='The day this way of counting starts to apply. Days before it keep theirs.', verbose_name='in force since')),
                ('break_counts_as_work', models.BooleanField(verbose_name='the break counts as working time')),
                ('max_open_hours', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='longest a working day may stay open (hours)')),
                ('note', models.CharField(blank=True, help_text='What agreement or decision this comes from.', max_length=300, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='declared by')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computation_rule_changes', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'change in how time is counted',
                'verbose_name_plural': 'changes in how time is counted',
                'ordering': ['-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'effective_from'), name='one_computation_change_per_day')],
            },
        ),
    ]
