# Generated by Django 6.1 on 2026-08-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0025_computationrulechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='record_retention_years',
            field=models.PositiveSmallIntegerField(default=4, help_text='How long clock events are kept, after which they are deleted. Four years is the floor set by art. 34.9 ET; a longer period needs its own justification, since keeping data because it might be useful is not a basis. Leave and contracts are not affected: they are not the working time record and they do not live off this period.', verbose_name='record retention (years)'),
        ),
    ]
