# Generated by Django 6.1 on 2026-08-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0026_alter_tenant_record_retention_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtimerules',
            name='irregular_settlement_months',
            field=models.PositiveSmallIntegerField(default=12, help_text='Art. 34.2 ET, unless the collective agreement says otherwise. 0 turns it off.', verbose_name='settle irregular hours within (months)'),
        ),
    ]
