# Generated by Django 6.1 on 2026-08-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0027_workingtimerules_irregular_settlement_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtimerules',
            name='special_regime',
            field=models.CharField(blank=True, choices=[('', 'General rules'), ('URBAN_PROPERTY', 'Caretaking of urban property'), ('GUARDS', 'Guards and security'), ('FARMING', 'Farm work'), ('RETAIL_HOSPITALITY', 'Retail and hospitality'), ('ROAD_TRANSPORT', 'Road transport'), ('RAIL', 'Rail transport'), ('SEA', 'Work at sea'), ('AIR', 'Air transport'), ('HEALTHCARE', 'Healthcare, with on-call duty'), ('HAZARDOUS', 'Exposure to environmental hazards'), ('COLD_STORAGE', 'Cold storage rooms'), ('MINING', 'Mining and underground work'), ('CONSTRUCTION', 'Construction and public works')], default='', help_text='RD 1561/1995. It changes no figure by itself: it says why yours differ.', max_length=20, verbose_name='special working time regime'),
        ),
        migrations.AddField(
            model_name='workingtimerules',
            name='standby_weekly_hours',
            field=models.PositiveSmallIntegerField(default=20, help_text='Art. 8.b RD 1561/1995, road transport only. 0 turns it off.', verbose_name='on-call hours a week, monthly average'),
        ),
    ]
