# Generated by Django 6.1 on 2026-08-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0028_workingtimerules_special_regime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtimerules',
            name='overtime_rest_days',
            field=models.PositiveSmallIntegerField(default=120, help_text='Art. 35.1 ET gives four months from the day the overtime was worked, unless the collective agreement says otherwise. 0 turns it off.', verbose_name='give back overtime rest within (days)'),
        ),
    ]
