# Generated by Django 6.1 on 2026-08-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0029_workingtimerules_overtime_rest_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtimerules',
            name='holiday_rest_multiplier',
            field=models.DecimalField(decimal_places=2, default=1, help_text='1 gives back the same time; agreements often say 1.5 or 1.75. Only used when holidays are made up with rest.', max_digits=4, verbose_name='hours of rest per hour worked on a holiday'),
        ),
        migrations.AddField(
            model_name='workingtimerules',
            name='holiday_worked_compensation',
            field=models.CharField(blank=True, choices=[('REST', 'rest'), ('PAID', 'pay')], default='', help_text='Art. 37.2 ET does not say: the collective agreement does. Empty means nothing is tracked, because there would be no figure to track it with.', max_length=8, verbose_name='a public holiday worked is made up with'),
        ),
    ]
