# Generated by Django 6.1 on 2026-08-28 22:32

import apps.tenants.rules
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0030_workingtimerules_holiday_rest_multiplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtimerules',
            name='seniority_leave',
            field=models.JSONField(blank=True, default=list, help_text='From the collective agreement, not the law. Empty means none: years of service add nothing to the holiday allowance.', validators=[apps.tenants.rules.validate_seniority_leave], verbose_name='extra holiday by seniority'),
        ),
    ]
