# Generated by Django 6.1 on 2026-08-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0031_workingtimerules_seniority_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtimerules',
            name='night_rest_multiplier',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Only used when night work is made up with rest.', max_digits=4, verbose_name='hours of rest per hour worked at night'),
        ),
        migrations.AddField(
            model_name='workingtimerules',
            name='night_worked_compensation',
            field=models.CharField(blank=True, choices=[('REST', 'rest'), ('PAID', 'a specific payment'), ('SALARY', 'nothing: the salary already accounts for it')], default='', help_text='Art. 36.2 ET leaves it to the collective agreement. Empty means nothing is tracked, because there would be no figure to track it with.', max_length=8, verbose_name='night work is made up with'),
        ),
    ]
