# Generated by Django 6.1 on 2026-09-17 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0032_workingtimerules_night_rest_multiplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SsoProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name, e.g. 'GreenCityControl'.", max_length=120, verbose_name='name')),
                ('issuer', models.CharField(help_text='Exactly the `iss` of its tokens, e.g. https://gcc.example/o.', max_length=255, verbose_name='issuer')),
                ('jwks_uri', models.URLField(blank=True, help_text="Where its public keys are. Blank derives it from the issuer's discovery document.", verbose_name='keys')),
                ('audience', models.CharField(blank=True, help_text="What its tokens must carry in `aud` for this install. Blank accepts the issuer's own.", max_length=255, verbose_name='audience')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('may_act_for_people', models.BooleanField(default=False, help_text='Lets its server exchange a signed assertion for a session of one of its people, with no browser. A managing application that clocks in on their behalf needs it; off by default.', verbose_name='may act for its people')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'identity provider',
                'verbose_name_plural': 'identity providers',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'issuer'), name='unique_issuer_per_company')],
            },
        ),
    ]
