# Generated by Django 6.1 on 2026-09-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0033_identity_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='punch_entry',
            field=models.CharField(choices=[('ANY', 'The interface and any integrated application'), ('APPLICATION', 'Preferably the integrated application'), ('TERMINAL_ONLY', 'Shared terminals only')], default='ANY', help_text='When a managing application is the one that knows the context of each punch (which site, which job), a punch made here arrives without it. Setting this to the application moves the button in this interface out of the way -- it does **not** remove it: if the application is unavailable, somebody would be working with no way to record their day, and the system that answers to an inspection is this one.', max_length=16, verbose_name='how people clock in'),
        ),
    ]
