# Generated by Django 6.1 on 2026-09-17 20:42

import apps.common.crypto
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0034_punch_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SsoDomain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('domain', models.CharField(help_text='Just the domain, lowercase and without the @: contrata.example', max_length=255, verbose_name='domain')),
            ],
            options={
                'verbose_name': 'federated domain',
                'verbose_name_plural': 'federated domains',
                'ordering': ['domain'],
            },
        ),
        migrations.AddField(
            model_name='ssoprovider',
            name='auto_provision',
            field=models.BooleanField(default=False, help_text='On: somebody signing in for the first time gets an account here, with no permissions and no working time set. Off: only people already here can sign in.', verbose_name='create people on first sign-in'),
        ),
        migrations.AddField(
            model_name='ssoprovider',
            name='client_id',
            field=models.CharField(blank=True, help_text='What this install is registered as at the provider. Only for the browser flow.', max_length=255, verbose_name='client id'),
        ),
        migrations.AddField(
            model_name='ssoprovider',
            name='client_secret',
            field=apps.common.crypto.EncryptedTextField(blank=True, default='', help_text='Stored encrypted; never sent to the browser. Only for the browser flow.', verbose_name='client secret'),
        ),
        migrations.AddField(
            model_name='ssoprovider',
            name='discovery_url',
            field=models.URLField(blank=True, help_text='Blank derives it from the issuer, which is the usual case.', verbose_name='discovery document'),
        ),
        migrations.AddField(
            model_name='ssoprovider',
            name='email_claim',
            field=models.CharField(choices=[('email', 'email'), ('preferred_username', 'preferred_username'), ('upn', 'upn')], default='email', help_text='Which claim holds the routable address. Ask the provider; they differ.', max_length=32, verbose_name='claim carrying the email'),
        ),
        migrations.AddField(
            model_name='ssoprovider',
            name='provider_enforces_mfa',
            field=models.BooleanField(default=True, help_text='Evidence that federated sign-ins are still two-factor, for an audit.', verbose_name='the provider guarantees the second factor'),
        ),
        migrations.AddField(
            model_name='ssoprovider',
            name='scopes',
            field=models.CharField(default='openid email profile', help_text='Space separated, as asked for at the authorisation endpoint.', max_length=255, verbose_name='scopes'),
        ),
        migrations.AddField(
            model_name='ssoprovider',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Stable name used in the sign-in URLs. Blank derives it from the name.', max_length=60, verbose_name='identifier'),
        ),
        migrations.AddConstraint(
            model_name='ssoprovider',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_provider_slug_per_company'),
        ),
        migrations.AddField(
            model_name='ssodomain',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.ssoprovider', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='ssodomain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company'),
        ),
        migrations.AddConstraint(
            model_name='ssodomain',
            constraint=models.UniqueConstraint(fields=('tenant', 'domain'), name='unique_domain_per_company'),
        ),
    ]
