# Generated by Django 6.1 on 2026-09-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0035_sso_browser_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='offline_punch_grace_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='Somebody clocking in out in the field with no signal stays queued on their device and arrives late. Within this many hours the punch is accepted with the time the device declares, and both times are kept. Past it, it goes through the correction flow instead, where somebody approves it and that is on the record. Zero means every punch counts from when it reached the server.', verbose_name='how late an offline punch may arrive'),
        ),
    ]
