# Generated by Django 6.1 on 2026-09-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0036_tenant_offline_punch_grace_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssoprovider',
            name='name',
            field=models.CharField(help_text="Display name, e.g. 'Company directory'.", max_length=120, verbose_name='name'),
        ),
    ]
