# Generated by Django 6.1 on 2026-08-12 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0009_tenant_payroll_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('period_start', models.DateField(verbose_name='from')),
                ('period_end', models.DateField(verbose_name='to')),
                ('total_seconds', models.PositiveIntegerField(default=0, verbose_name='hours in the period')),
                ('overtime_seconds', models.PositiveIntegerField(default=0, verbose_name='overtime in the period')),
                ('fingerprint', models.CharField(max_length=64, verbose_name='document fingerprint')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_summaries', to=settings.AUTH_USER_MODEL, verbose_name='employee')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_summaries_generated', to=settings.AUTH_USER_MODEL, verbose_name='generated by')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant', verbose_name='company')),
            ],
            options={
                'verbose_name': 'payroll summary',
                'verbose_name_plural': 'payroll summaries',
                'ordering': ['-period_end', 'employee'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'period_start', 'period_end'), name='one_payroll_summary_per_person_and_period')],
            },
        ),
    ]
